PT100:
  Twarm: AIN0
  Tcold: AIN1
  Tout: AIN2
  h35mm: AIN3
  h65mm: AIN4
  h95mm: AIN5
  h125mm: AIN6
  h155mm: AIN7
  h185mm: AIN8
  h215mm: AIN9
Flowmeter:
  warmMassflow: AIN11
  coldMassflow: AIN13
Switch:
  bypass: AIN10