# Experiment configuration file
COMMENT: 'A clever comment of the experiment I have made ;-)'

# Measurement
SAMPLE_RATE: 3 # maximum of 4

# Setup
INLET: 'single' # (ring, single)
OUTLET: 'middle' # (top, middle, bottom)
THERMOSTAT: 60 # heater thermostat setting


