# Experiment configuration file
#COMMENT: 'A clever comment of the experiment I have made ;-)'
COMMENT: 'First test with stirrer'
# Measurement
SAMPLE_RATE: 3 # maximum of 3

# Setup
INLET: 'ring' # (ring, single)
OUTLET: 'middle' # (top, middle, bottom)
THERMOSTAT: 50 # heater thermostat setting


